#+TITLE: CS524 Homework #1
#+STARTUP: noindent showall
#+OPTIONS: toc:nil num:nil
#+LaTeX_HEADER: \usepackage[margin=1.0in]{geometry}
#+LaTeX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \renewcommand{\Large}{\small}
#+LATEX_HEADER: \usepackage[table]{xcolor}
#+LaTeX_HEADER: \setlength\parindent{0pt}


* (1) Using the formulae for the first software business model, find the year where the cumulative support expense equals that of the initial licensing fee $p$, where $p = \textdollar 12000$ per user and $c = 0.40$. In how many years will the initial cost of software become $5\%$ of the overall expenditure?

#+ATTR_LaTeX: :align c|c
| *Part 1*               | *Part 2*                    |
|------------------------+-----------------------------|
| $np = npmc$            | $np = (0.05)np(1 + mc)$     |
| $1 = mc$               | $1 = (0.05)(1 + (m)(0.40))$ |
| $m = \frac{1}{0.40}$   | $20 = 1 + (m)(0.40)$        |
| $m = \bold{2}$ *years* | $19 = m(0.40)$              |
|                        | $m = \frac{19}{0.40}$       |
|                        | $m = \bold{47.5}$ *years*   |

* (2) In the definition of /Hybrid Cloud/, a term "cloud bursting" is mentioned. Search the Web for its definitions. Do these definitions agree? If so, provide what you think is the best definition (you can rephrase as you see fit). If not, explain the differences between the definitions.

#+ATTR_LaTeX: :align c|p{8cm}
|                                                      | <30>                           |
| *Source*                                             | *Definition*                   |
|------------------------------------------------------+--------------------------------|
| [[https://azure.microsoft.com/en-us/overview/what-is-cloud-bursting/][Azure Docs]]                                           | a configuration that’s set up between a private cloud and a public cloud to deal with peaks in IT demand |
|------------------------------------------------------+--------------------------------|
| \cellcolor{yellow!5} [[https://www.service-architecture.com/articles/cloud-computing/cloud_bursting.html][Blog About Service Architecture]] | \cellcolor{yellow!5} if a situation arises where the application needs additional resources, it can "burst" into the public cloud and use Cloud Computing for those additional resources. |
|------------------------------------------------------+--------------------------------|
| [[https://www.upwork.com/hiring/development/is-cloud-bursting-right-for-you/][Upwork Article]]                                       | allows an organization to rent additional storage and compute resources on demand |

These definitions do agree, and the best definition in my opinion is the *second*, because it provides both the definition AND the reason why one might want to implement cloud bursting into their application.

* (3) What are the essential differences between the /public/ and /private/ cloud that have made CIOs worry about the legal consequences of Shadow IT? Read the original text of the US government acts mentioned in the text (HIPAA and SOX) and summarize each in one paragraph.
- /Private cloud/ is provisioned for exclusive use by a single organization comprising multiple consumers, such as different units of the business. /Public cloud/ is provisioned for open use by the general public. With /Shadow IT/, CIOs lose control over personnel, and introduce security risks into their system because their data becomes replicated in the Cloud. True private clouds can limit the ability of developers to use the tools and resources they need, but public clouds leave the company vulnerable to the risks that Shadow IT without internal controls and supervision introduces.
- /HIPAA/, or the US Health Insurance Portability and Accountability Act, was a government act designed to implement national standards for the protection of health care information. It enforces a "privacy rule" that aims to strike a balance between protecting the healthcare information of an individual and allowing the flow of health information needed to promote high-quality health care and preserve the public health. It applies to health plans, health care providers, and health care clearing houses. It protects any individually identifiable health information, but does not restrict the use of de-identified health information. The act also details the multitude of penalties imposed upon violators of the act, depending on the severity of the unlawful disclosure.
- /SOX/, or the Sarbanes-Oxley Act, sets standards for all US public companies' boards and accounting firms. It was part of the government's response to a number of corporate and accounting scandals such as those of Enron and WorldCom. It covers the responsibilities imposed upon the board of directors of publicly held companies, and gives the SEC the power to impose additional restrictions and regulations on these companies. The responsibilities of the boards and accounting firms include producing accurate financial disclosures, preventing the manipulation of audits, and reporting on the adequacy of the internal accounting controls (such as determining fraud risk, tracing the flow of internal transactions, etc). 
  
* Consider the case of /Instagram/ as described in the textbook. How many employees and customers did it have at the time of the purchase by Facebook? How much did Facebook pay for it? What was the value that the purchased business has generated in the first two years, and what were the factors that enabled generating this value?
At the time that it was purchased by Facebook, Instagram has eleven employees that were managing thirty million customers.\\
Facebook paid one billion dollars for the company.\\
In the first two years, the company generated one billion dollars in value.\\
It was able to generate so much in so little time because the operating cost was so low; there were no physical servers to maintain, there were no technicians required for the administration of the servers, there was no capital expense required. The company had no physical infrastructure, and only three employees of the eleven were managing the infrastructure through the Amazon Cloud. They had almost no investment in people or infrastructure, so they were able to direct most of their capital toward customer acquisition and retention.

* (5) Familiarize yourself with the [[https://aws.amazon.com/ec2/][description of /Amazon Elastic Cloud Computing/]]. What kind of service model does it provide (i.e. SaaS, PaaS, IaaS, or a combination of these). Please list the features that support your answer.
Amazon Elastic Cloud Computing is a service that provides dynamic scaling of computing capacity depending on the needs of the consumer. It can scale both up (to react to increasing demand) or down (to reduce costs when there is a decrease in demand).\\
The service follows the IaaS model most closely. IaaS provides the consumer the capability to provision processing, storage, networks, and other fundamental computing resources so that the consumer can deploy and run arbitrary software, without having to control and manage the underlying cloud infrastructure. AWS has distributed services and elastic scaling, for provisioning processing power dynamically. They provide complete control so that consumers can deploy and run arbitrary software, leverage network capabilities, as well as create users with different roles. It is inexpensive and has varied pricing, allowing the consumer to only pay for the infrastructure that they use.

* (6) Read the article on Fog Computing provided in the lecture. Familiarize yourself with the [[https://openfogconsortium.org][OpenFog Consortium]] and answer the following questions:
*/(a)/ How many members does the consortium have?*
       - over 470 members worldwide
*/(b)/ What is the definition of Fog computing according to the consortium?*
       - Fog computing is a system-level horizontal architecture that distributes resources and services of computing, storage, control and networking anywhere along the continuum from Cloud to Things. Essentially, it bridges the gap between the cloud and hardware horizontally over a network stack, allowing a greater amount of integration and efficiency.
*/(c)/ What is the goal of the consortium?*
       - The goals of the consortium are to enable interoperability and scalability by creating an open architecture. They want to identify, share, and apply the best practices for fog computing across academia and industry. Eventually, they believe that their work can create new business models, growth, and industries.
         
* (7) Consider the example of /Zing Interactive Media/ and explain how you would launch the same service today using Amazon EC2. Specifically list the steps (and costs) you would avoid by doing so.
Zing Interactive Media had a lot of major, non-user-facing investments that were required to keep the service running. They needed to rent a cage on an AT&T hosting facility, develop redundancies for increases in demand, provide fixed specifications for the compute resources they needed, determine (on their own) the number of servers they needed and pay for the ones that idled, purchase gear and software for each of their server spaces, and deploy and maintain the actual software that comprised their service.\\
Using Amazon EC2, I could cut costs on unused server space by taking advantage of their dynamic scale-up, scale-down services. I could avoid the steps of having to determine the needs of my service and picking out server specifications accordingly. I could avoid the step of having to purchase software and gear for the physical server space, and could completely skip the necessity of having to lease out T1 lines. Instead of spending money on an IT team (system administrators, database developers, etc) to maintain and create my infrastructure, I could leverage EC2's built-in capabilities and spend that money on marketing or hiring software developers instead.

* (8) Explain what /CPU pinning/ is and how /Intel/ supports it with API.
CPU pinning is the act of assigning a virtual machine to a given processor or a range of processes for the sake of guaranteeing a certain percentage of the CPU to a given virtual machine. Intel providing an API so that you can send a request to the Cloud provider to associate a virtual machine to a set of processes or a processor, ensuring that it has the resources it needs to be performant at scale.

* (9) Study the Amazon EC2 SLA. What service commitment (in percentage) does it guarantee? What is the bound on the downtime in a year?
- Amazon's SLA dictates that they have 99.99% uptime every month. For any downtime beyond that SLA, the consumer is granted some service credit (10% for uptime between 99.99% and 99%, 30% for uptime below 99%).
- The upper bound on downtime for a year is 0.01%, or about 0.876 hours, or about 52 minutes and 33.6 seconds.
- [[https://aws.amazon.com/compute/sla/][Source for SLA]]
  
* (10) What is the "telecom-grade" service commitment? Who were the ETSI NFV Industry Specifications Group founders? List the areas where the NFV is expected to act.
- The telecom-grade service commitment equates to the hardware being specifically engineered for use in the telecom industry and network, for at least 15 years, and having 99.999% uptime. Though these features require a high cost of installation and maintenance, they ensure that the service is robust and highly available for critical applications.
- To overcome the problem of costs and lack of standardization, the ETSI NFV Industry Specifications Group was formed, initially consisting of seven of the world's leading telecom network operators, but then expanding by 52 more groups including equipment manufacturers, IT vendors, and consultants. They released a white paper in late 2012 outlining the set of standards for the advancement of network service virtualization.
- They act in the following areas: operational improvements, cost reductions (replacement, equipment, maintenance), streamlining high-touch processes, and reduction of development time.
